language: java
sudo: false # faster builds

script: "mvn integration-test"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
  email:
    on_success: never
    on_failure: change
